export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        'tertiary-fixed': '#e2e2e5',
        'primary-fixed-dim': '#00dbe9',
        'tertiary-fixed-dim': '#c6c6c9',
        'on-tertiary-fixed': '#1a1c1e',
        'secondary-fixed': '#e2e2e4',
        error: '#ba1a1a',
        'surface-container-lowest': '#ffffff',
        'outline-variant': '#b9cacb',
        'on-secondary-container': '#616365',
        'on-primary': '#ffffff',
        'surface-bright': '#fcf8f9',
        'inverse-surface': '#313031',
        'tertiary-container': '#d9d9dc',
        'on-tertiary': '#ffffff',
        'on-background': '#1c1b1c',
        'on-tertiary-fixed-variant': '#454749',
        background: '#fcf8f9',
        'surface-container-low': '#f6f3f4',
        'on-surface-variant': '#3b494b',
        'surface-variant': '#e5e2e3',
        'primary-fixed': '#7df4ff',
        'on-tertiary-container': '#5d5f61',
        outline: '#6a7a7b',
        'secondary-container': '#dfdfe1',
        'surface-dim': '#dcd9da',
        secondary: '#5d5e60',
        'surface-container-highest': '#e5e2e3',
        'on-secondary-fixed-variant': '#454749',
        tertiary: '#5d5e61',
        'inverse-on-surface': '#f3f0f1',
        'surface-container-high': '#ebe7e8',
        'on-primary-container': '#006970',
        primary: '#006970',
        surface: '#fcf8f9',
        'on-secondary': '#ffffff',
        'on-secondary-fixed': '#1a1c1d',
        'error-container': '#ffdad6',
        'on-primary-fixed-variant': '#004f54',
        'surface-container': '#f0edee',
        'secondary-fixed-dim': '#c6c6c8',
        'on-surface': '#1c1b1c',
        'inverse-primary': '#00dbe9',
        'primary-container': '#00f0ff',
        'on-error-container': '#93000a',
        'on-primary-fixed': '#002022',
        'surface-tint': '#006970',
        'on-error': '#ffffff'
      },
      fontFamily: {
        display: ['Sora', 'sans-serif'],
        'label-caps': ['Sora', 'sans-serif'],
        'body-md': ['Sora', 'sans-serif'],
        'body-sm': ['Sora', 'sans-serif'],
        'headline-sm': ['Sora', 'sans-serif'],
        'headline-md': ['Sora', 'sans-serif'],
        'headline-lg': ['Sora', 'sans-serif']
      },
      fontSize: {
        'label-caps': ['12px', { lineHeight: '1', letterSpacing: '0.05em', fontWeight: '700' }],
        'body-sm': ['14px', { lineHeight: '1.5', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'headline-sm': ['20px', { lineHeight: '1.4', fontWeight: '500' }],
        'headline-md': ['24px', { lineHeight: '1.3', fontWeight: '600' }],
        'headline-lg': ['32px', { lineHeight: '1.2', fontWeight: '600', letterSpacing: '-0.01em' }]
      },
      spacing: {
        xs: '4px',
        base: '8px',
        sm: '12px',
        md: '24px',
        lg: '48px',
        xl: '80px',
        gutter: '24px',
        margin: '32px'
      }
    }
  },
  plugins: []
};
