function OrderItemsModal({ isOpen, order, onClose }) {
  if (!isOpen || !order) return null;
  const totalQty = order.orderItems.reduce((sum, item) => sum + item.quantity, 0);
  const totalAmount = order.orderItems.reduce((sum, item) => sum + item.quantity * item.unitPrice, 0);
  return <div className="fixed inset-0 z-[78] modal-backdrop overflow-y-auto p-4 md:p-8"><div className="min-h-full w-full flex items-center justify-center"><div className="glass-panel w-full max-w-4xl rounded-2xl p-6 md:p-8 shadow-2xl"><div className="flex items-start justify-between gap-3 mb-5"><div><h3 className="font-headline-md text-headline-md">Order items</h3><p className="text-body-sm text-on-surface-variant mt-xs">Read-only order item detail.</p></div><button type="button" className="p-2 rounded-lg hover:bg-primary/5 transition-colors" onClick={onClose} aria-label="Close order items popup"><span className="material-symbols-outlined text-on-surface-variant">close</span></button></div><div className="grid grid-cols-1 md:grid-cols-4 gap-3 mb-4"><div className="rounded-xl border border-outline-variant/30 bg-surface-container-low p-sm"><p className="font-label-caps text-[10px] text-on-surface-variant uppercase">Order ID</p><p className="font-headline-sm text-headline-sm">{order.id}</p></div><div className="rounded-xl border border-outline-variant/30 bg-surface-container-low p-sm"><p className="font-label-caps text-[10px] text-on-surface-variant uppercase">Items</p><p className="font-headline-sm text-headline-sm">{order.orderItems.length}</p></div><div className="rounded-xl border border-outline-variant/30 bg-surface-container-low p-sm"><p className="font-label-caps text-[10px] text-on-surface-variant uppercase">Quantity</p><p className="font-headline-sm text-headline-sm">{totalQty}</p></div><div className="rounded-xl border border-outline-variant/30 bg-surface-container-low p-sm"><p className="font-label-caps text-[10px] text-on-surface-variant uppercase">Total</p><p className="font-headline-sm text-headline-sm">${totalAmount.toFixed(2)}</p></div></div><div className="overflow-x-auto rounded-xl border border-outline-variant/30"><table className="w-full text-left"><thead><tr className="border-b border-outline-variant/30 font-label-caps text-[10px] text-on-surface-variant"><th className="py-sm px-sm">#</th><th className="py-sm px-sm">PRODUCT</th><th className="py-sm px-sm">QTY</th><th className="py-sm px-sm">UNIT PRICE</th><th className="py-sm px-sm">TOTAL</th></tr></thead><tbody className="text-body-sm">{order.orderItems.map((item, index) => <tr key={`${item.name}-${index}`} className="border-b border-outline-variant/20"><td className="py-sm px-sm">{index + 1}</td><td className="py-sm px-sm">{item.name}</td><td className="py-sm px-sm">{item.quantity}</td><td className="py-sm px-sm">${item.unitPrice.toFixed(2)}</td><td className="py-sm px-sm">${(item.quantity * item.unitPrice).toFixed(2)}</td></tr>)}</tbody></table></div><div className="flex items-center justify-end gap-2 pt-5"><button type="button" onClick={onClose} className="px-md py-sm rounded-xl border border-outline-variant/40 font-label-caps text-label-caps hover:bg-surface-container-low transition-colors">
              CLOSE
            </button></div></div></div></div>;
}
export {
  OrderItemsModal
};
